name: Rust

on:
  push:
  
    branches: [ "main" ]
    tags: v*
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone it
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'mat-1'
        repository: 'minecraft-scans'
    
    #- name: download
    #  run: curl https://github.com/mat-1/minecraft-scans/raw/main/ips -o ${GITHUB_WORKSPACE}/ips
    - name: Run
      run: cargo run --release
    #- name: upload output
    #  run: gh release create ${GITHUB_WORKSPACE}/output.txt output.txt --latest
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./target/release/output.txt
