name: Rust

on:
  push:
  
    branches: [ "main" ]
    tags: v*
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone it
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'mat-1'
        repository: 'minecraft-scans'
    
    - name: Access cloned repository content
      run: |
        cd minecraft-scans
        ls -la
        cp ips /home/runner/work/minecraft-scan-decompress/minecraft-scan-decompress

    - name: Run
      run: cargo run --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: output.txt
