name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: download
      run: curl https://github.com/mat-1/minecraft-scans/raw/main/ips -o ./${GITHUB_WORKSPACE}
    - uses: actions/checkout@v3
    - name: Run
      run: cargo run --verbose
      
